{% set base_name = "libignition-msgs" %}
{% set version = "1.0.0" %}
{% set name = base_name + version.split('.')[0] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-msgs/archive/ignition-msgs{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: aaf7b13e93d08b36c753d537ebc5ac80638ce4e934e0a1589196a7073bb1d420

build:
  number: 3
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - vs2017_win-64                      # [win64]
    - vs2017_win-32                      # [win32]
    - make                               # [not win]
    - cmake
    - pkg-config
  host:
    - libignition-tools
    - libignition-math4
    - protobuf
    - libprotobuf                        # [not win]
  run:
    - libignition-tools
    - libignition-math4
    - protobuf
    - libprotobuf                        # [not win]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/msgs1/ignition/msgs.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-msgs1.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-msgs1.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-msgs1/ignition-msgs1-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\\msgs1\\ignition\\msgs.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-msgs1.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-msgs1.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-msgs1\\ignition-msgs1-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://bitbucket.org/ignitionrobotics/ign-msgs
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Ignition Messages'

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
    - Tobias-Fischer
