{% set base_name = "libignition-msgs" %}
{% set version = "8_8.7.0" %}
{% set name = base_name + version.split('_')[0] %}

package:
  name: {{ name }}
  version: {{ version.split('_')[1] }}

source:
  - url: https://github.com/gazebosim/gz-msgs/archive/ignition-msgs{{ version }}.tar.gz
    sha256: a16528383745f827af7656ac799ab1f2272678b4584454d0c9e56e3bd22d9fcb
    patches:
      - 346.patch

build:
  number: 13
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make                               # [not win]
    - cmake
    - pkg-config
    # We need all host deps also in build for cross-compiling
    - libignition-math6  # [build_platform != target_platform]
    - libignition-tools1  # [build_platform != target_platform]
    - tinyxml2  # [build_platform != target_platform]
    - libabseil  # [build_platform != target_platform]
    - libprotobuf  # [build_platform != target_platform]
  host:
    - libignition-math6 >=6.4
    - libignition-tools1
    - tinyxml2
    - libabseil
    - libprotobuf
  run:

test:
  commands:
    - test -f ${PREFIX}/include/ignition/msgs{{ version.split('_')[0] }}/ignition/msgs.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-msgs{{ version.split('_')[0] }}.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-msgs{{ version.split('_')[0] }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-msgs{{ version.split('_')[0] }}/ignition-msgs{{ version.split('_')[0] }}-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\\msgs{{ version.split('_')[0] }}\\ignition\\msgs.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-msgs{{ version.split('_')[0] }}.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-msgs{{ version.split('_')[0] }}.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-msgs{{ version.split('_')[0] }}\\ignition-msgs{{ version.split('_')[0] }}-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-msgs
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Messages

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
    - Tobias-Fischer
