{% set base_name = "libignition-msgs" %}
{% set version = "7.0.0" %}
{% set name = base_name + version.split('.')[0] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-msgs/archive/ignition-msgs{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: d303d2060d59f7bf834ece734f83d3b12db906f031ad98a19e694cd67855e691

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make                               # [not win]
    - cmake
    - pkg-config
  host:
    - libignition-math6 >=6.4
    - libignition-tools1
    - tinyxml2
    - libprotobuf


test:
  commands:
    - test -f ${PREFIX}/include/ignition/msgs{{ version.split('.')[0] }}/ignition/msgs.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-msgs{{ version.split('.')[0] }}.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-msgs{{ version.split('.')[0] }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-msgs{{ version.split('.')[0] }}/ignition-msgs{{ version.split('.')[0] }}-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\\msgs{{ version.split('.')[0] }}\\ignition\\msgs.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-msgs{{ version.split('.')[0] }}.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-msgs{{ version.split('.')[0] }}.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-msgs{{ version.split('.')[0] }}\\ignition-msgs{{ version.split('.')[0] }}-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-msgs
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Messages

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
    - Tobias-Fischer
