bot:
  abi_migration_branches:
  - v5.3.0
  - v7
  automerge: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
